title.info=title.info
title.warn=title.warn
title.confirm=title.confirm
title.settings=title.settings
title.people=title.people
title.bonuses=title.bonuses
title.rooms=title.rooms
title.compute=title.compute

button.browse=button.browse
button.test=button.test
button.add=button.add
button.export=button.export
button.exportall=button.exportall
button.viewall=button.viewall
button.delete=button.delete
button.restore=button.restore
button.deleteall=button.deleteall
button.printall=button.printall

# Settings
set.preference=set.preference
set.nonPreference=set.nonPreference
set.unfulfilledPreference=set.unfulfilledPreference
set.mutualPreference=set.mutualPreference
set.ageDiff=set.ageDiff
set.largeAgeDiff=set.largeAgeDiff
set.sameLocation=set.sameLocation
set.sameGender=set.sameGender

set.largeGroup=set.largeGroup
set.underoccupancy=set.underoccupancy
set.criticalOccupancy=set.criticalOccupancy

set.ageDiffThr=set.ageDiffThr
set.largeAgeDiffThr=set.largeAgeDiffThr
set.largeGroupThr=set.largeGroupThr
set.largeGroupAgeLimit=set.largeGroupAgeLimit

set.useEarlyPrune=set.useEarlyPrune
set.earlyPruneStrength=set.earlyPruneStrength
set.earlyPruneLength=set.earlyPruneLength

desc.pairwise=desc.pairwise
desc.preference=desc.preference
desc.nonPreference=desc.nonPreference
desc.unfulfilledPreference=desc.unfulfilledPreference
desc.mutualPreference=desc.mutualPreference
desc.ageDiff=desc.ageDiff
desc.largeAgeDiff=desc.largeAgeDiff
desc.sameLocation=desc.sameLocation
desc.sameGender=desc.sameGender

desc.roomwise=desc.roomwise
desc.largeGroup=desc.largeGroup
desc.underoccupancy=desc.underoccupancy
desc.criticalOccupancy=desc.criticalOccupancy

desc.pruning=desc.pruning

set.reset=set.reset
set.apply=set.apply
set.info=set.info

set.pts=set.pts
set.ptsperyear=set.ptsperyear
set.years=set.years
set.prefs=set.prefs
set.iterations=set.iterations

msg.reset=msg.reset
msg.set=msg.set

# People
ppl.import=ppl.import
ppl.group=ppl.group
ppl.name=ppl.name
ppl.birth=ppl.birth
ppl.location=ppl.location
ppl.gender=ppl.gender
ppl.prefs=ppl.prefs

col.group=col.group
col.name=col.name
col.birth=col.birth
col.gender=col.gender
col.location=col.location
col.prefs=col.prefs

ppl.importtooltip=ppl.importtooltip

# Custom bonuses
cbs.title=cbs.title

cbs.score=cbs.score
cbs.negativeInfinity=cbs.negativeInfinity
cbs.negInfTooltip=cbs.negInfTooltip

# Rooms
rms.import=rms.import
rms.id=rms.id
rms.capacity=rms.capacity

col.id=col.id
col.capacity=col.capacity

rms.importtooltip=rms.importtooltip

# Compute
cmp.exec=cmp.exec
col.size=col.size
col.occupants=col.occupants

exp.all=exp.all
exp.result=exp.result
exp.end=exp.end

# Msgs

desc.csvfilter=desc.csvfilter
desc.txtfilter=desc.txtfilter
msg.err=msg.err
msg.illegalCsvFormat=msg.illegalCsvFormat
msg.personAlreadyExists=msg.personAlreadyExists
msg.personDoesNotExist=msg.personDoesNotExist
msg.prefDoesNotExist=msg.prefDoesNotExist
msg.pairHasValue=msg.pairHasValue
msg.exportFail=msg.exportFail
msg.noCSVExt=msg.noCSVExt
msg.noTXTExt=msg.noTXTExt
msg.noPeople=msg.noPeople
msg.noRooms=msg.noRooms
msg.noPeopleSelected=msg.noPeopleSelected
msg.noRoomsSelected=msg.noRoomsSelected
msg.noPairsSelected=msg.noPairsSelected

msg.seeConsoleLog=msg.seeConsoleLog
# %1 long amt paths processed %2 long elapsed ms %3 long remaining ns (remainder) %4 long amt Paths/sec
msg.performanceReport=msg.performanceReport

msg.deletePpl=msg.deletePpl
msg.deleteRooms=msg.deleteRooms
